"""
Product Quick Add Dialog
"""
import time

from PyQt6 import QtCore, QtWidgets


class ProductQuickDialog(QtWidgets.QDialog):
    """Quick dialog for adding products on-the-fly during sales"""
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.result_data = None
        self.setup_ui()
    
    def setup_ui(self):
        """Setup the UI"""
        self.setWindowTitle("Agregar Producto Rápido")
        self.setMinimumWidth(350)
        
        layout = QtWidgets.QVBoxLayout(self)
        
        # Info label
        info = QtWidgets.QLabel("⚡ Agregar producto rápidamente")
        info.setStyleSheet("font-weight: bold; color: #2196F3;")
        layout.addWidget(info)
        
        # Form
        form = QtWidgets.QFormLayout()
        
        # SKU (auto-generated by default)
        self.sku_edit = QtWidgets.QLineEdit()
        self.sku_edit.setPlaceholderText(f"AUTO-{int(time.time())}")
        form.addRow("SKU:", self.sku_edit)
        
        # Name (required)
        self.name_edit = QtWidgets.QLineEdit()
        self.name_edit.setPlaceholderText("Nombre del producto *")
        form.addRow("Nombre:*", self.name_edit)
        
        # Price (required)
        self.price_spin = QtWidgets.QDoubleSpinBox()
        self.price_spin.setRange(0, 999999)
        self.price_spin.setPrefix("$ ")
        self.price_spin.setValue(0)
        form.addRow("Precio:*", self.price_spin)
        
        # Stock
        self.stock_spin = QtWidgets.QDoubleSpinBox()
        self.stock_spin.setRange(0, 999999)
        self.stock_spin.setValue(1)
        form.addRow("Stock:", self.stock_spin)
        
        # Category (simple text for now)
        self.category_edit = QtWidgets.QLineEdit()
        self.category_edit.setPlaceholderText("General")
        form.addRow("Categoría:", self.category_edit)
        
        layout.addLayout(form)
        
        # Note
        note = QtWidgets.QLabel("💡 Puedes editar más detalles después en Productos")
        note.setStyleSheet("font-size: 10px; color: #666;")
        layout.addWidget(note)
        
        # Buttons
        button_box = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.StandardButton.Ok |
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
        )
        button_box.accepted.connect(self.validate_and_accept)
        button_box.rejected.connect(self.reject)
        layout.addWidget(button_box)
        
        # Focus on name
        self.name_edit.setFocus()
    
    def validate_and_accept(self):
        """Validate and accept"""
        name = self.name_edit.text().strip()
        if not name:
            QtWidgets.QMessageBox.warning(self, "Error", "El nombre es obligatorio")
            self.name_edit.setFocus()
            return
        
        price = self.price_spin.value()
        if price <= 0:
            QtWidgets.QMessageBox.warning(self, "Error", "El precio debe ser mayor a 0")
            self.price_spin.setFocus()
            return
        
        # Generate SKU if empty
        sku = self.sku_edit.text().strip()
        if not sku:
            sku = f"AUTO-{int(time.time())}"
        
        self.result_data = {
            'sku': sku,
            'name': name,
            'price': price,
            'stock': self.stock_spin.value(),
            'category_id': 1,  # Default
            'department': self.category_edit.text().strip() or 'General'
        }
        
        self.accept()

    def showEvent(self, event):
        """Apply theme colors when dialog is shown."""
        super().showEvent(event)
        try:
            from app.utils.theme_manager import theme_manager
            c = theme_manager.get_colors()
            for btn in self.findChildren(QtWidgets.QPushButton):
                text = btn.text().lower()
                if any(w in text for w in ['guardar', 'save', 'aceptar', 'ok', 'crear', 'agregar']):
                    btn.setStyleSheet(f"background: {c['btn_success']}; color: white; font-weight: bold; padding: 8px; border-radius: 5px;")
                elif any(w in text for w in ['cancelar', 'cancel', 'cerrar', 'eliminar', 'delete']):
                    btn.setStyleSheet(f"background: {c['btn_danger']}; color: white; font-weight: bold; padding: 8px; border-radius: 5px;")
        except Exception:
            pass
